<#
    Maps settings managed by the app (Administrative Templates via
    registryKey/valueName, Security Settings via SecurityCatalog.ps1,
    Advanced Audit via AdvancedAuditCatalog.ps1) to CIS recommendations
    loaded from data/cis-index.json (generated by Build-CisIndex.ps1, see
    plan-gpedit-cis.md).

    The CIS index is never regenerated by GpEdit.ps1: unlike the
    ADMX/security indexes, its content doesn't depend on machine state,
    only on the versioned .audit files - regenerate manually
    (Build-CisIndex.ps1) only when new benchmarks are added.
#>

Set-StrictMode -Version Latest

# CIS vocabulary (password_policy / lockout_policy, SCREAMING_SNAKE_CASE) to
# SecurityCatalog.ps1 names (PascalCase). The two never align by
# construction (independent sources), hence this fixed table: CIS
# vocabulary for these ~10 settings has been stable since 2016 (checked
# against 15 available .audit files).
$script:CisPasswordLockoutKeyMap = @{
    PasswordHistorySize        = @{ Bucket = 'byPasswordPolicy'; Key = 'ENFORCE_PASSWORD_HISTORY' }
    MaximumPasswordAge         = @{ Bucket = 'byPasswordPolicy'; Key = 'MAXIMUM_PASSWORD_AGE' }
    MinimumPasswordAge         = @{ Bucket = 'byPasswordPolicy'; Key = 'MINIMUM_PASSWORD_AGE' }
    MinimumPasswordLength      = @{ Bucket = 'byPasswordPolicy'; Key = 'MINIMUM_PASSWORD_LENGTH' }
    PasswordComplexity         = @{ Bucket = 'byPasswordPolicy'; Key = 'COMPLEXITY_REQUIREMENTS' }
    ClearTextPassword          = @{ Bucket = 'byPasswordPolicy'; Key = 'REVERSIBLE_ENCRYPTION' }
    LockoutDuration            = @{ Bucket = 'byLockoutPolicy'; Key = 'LOCKOUT_DURATION' }
    LockoutBadCount            = @{ Bucket = 'byLockoutPolicy'; Key = 'LOCKOUT_THRESHOLD' }
    ResetLockoutCount          = @{ Bucket = 'byLockoutPolicy'; Key = 'LOCKOUT_RESET' }
    ForceLogoffWhenHourExpire  = @{ Bucket = 'byPasswordPolicy'; Key = 'FORCE_LOGOFF' }
}

function Import-CisIndex {
    <#
        Loads data/cis-index.json if present. Never regenerates it (see
        header comment): if missing, the CIS tab is just hidden everywhere
        (Get-CisRecommendation returns $null), without blocking app startup.

        Also applies "info" field overrides (data/cis-overrides.json, see
        plan-gpedit-security-catalog-editor.md §4.3) right after loading -
        on every launch, not just when Build-CisIndex.ps1 is manually rerun,
        so a UI edit stays visible without depending on a full regeneration.
    #>
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        Write-Warning "CIS index not found ($Path) - the 'CIS recommendation' tab will be hidden. Run Build-CisIndex.ps1 to generate it."
        return $null
    }
    try {
        $cisIndex = Get-Content -Raw -Encoding UTF8 -LiteralPath $Path | ConvertFrom-Json
        $overrides = Get-CisOverrides -DataPath (Split-Path -Parent $Path)
        Merge-CisOverrides -CisIndex $cisIndex -Overrides $overrides
        return $cisIndex
    }
    catch {
        Write-Warning "CIS index unreadable ($Path): $($_.Exception.Message) - the 'CIS recommendation' tab will be hidden."
        return $null
    }
}

# ---------------------------------------------------------------------------
# Live catalog editor - CIS "info" field overrides (see
# plan-gpedit-security-catalog-editor.md §4.3). data/cis-index.json is
# generated from .audit files (Build-CisIndex.ps1), so a manual edit
# written directly into it would be lost on the next regeneration.
# Overrides live in a separate file instead, keyed by "<bucket>::<key>"
# (same buckets/keys as cis-index.json), merged both here (Import-CisIndex,
# every launch) and in Build-CisIndex.ps1 (every full regeneration).
# ---------------------------------------------------------------------------

function Get-CisOverridesPath {
    param([string]$DataPath)
    return (Join-Path $DataPath 'cis-overrides.json')
}

function Get-CisOverrides {
    # Loads data/cis-overrides.json; missing/unreadable => no overrides
    # (same tolerance as a missing cis-index.json).
    param([string]$DataPath)
    $path = Get-CisOverridesPath -DataPath $DataPath
    if (-not (Test-Path -LiteralPath $path)) { return @{} }
    try {
        $raw = Get-Content -Raw -Encoding UTF8 -LiteralPath $path | ConvertFrom-Json
        $result = @{}
        foreach ($prop in $raw.PSObject.Properties) {
            $result[$prop.Name] = @{ info = $prop.Value.info }
        }
        return $result
    }
    catch {
        Write-Warning "CIS overrides unreadable ($path): $($_.Exception.Message) - ignored."
        return @{}
    }
}

function Set-CisOverride {
    <#
        Adds/replaces the "info" override of a CIS entry (identified by its
        bucket + key, from the resolved entry - see Get-CisRecommendationFor...
        in this file) and rewrites data/cis-overrides.json in full (small
        file, no performance concern).
    #>
    param(
        [Parameter(Mandatory)][string]$DataPath,
        [Parameter(Mandatory)][string]$Bucket,
        [Parameter(Mandatory)][string]$Key,
        [Parameter(Mandatory)][string]$Info
    )
    $path = Get-CisOverridesPath -DataPath $DataPath
    $overrides = Get-CisOverrides -DataPath $DataPath
    $overrides["$Bucket`::$Key"] = @{ info = $Info }

    $ordered = [ordered]@{}
    foreach ($k in ($overrides.Keys | Sort-Object)) { $ordered[$k] = $overrides[$k] }

    $outDir = Split-Path -Parent $path
    if (-not (Test-Path -LiteralPath $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
    $json = $ordered | ConvertTo-Json -Depth 5
    [System.IO.File]::WriteAllText($path, $json, (New-Object System.Text.UTF8Encoding($true)))
}

function Merge-CisOverrides {
    # Applies overrides ("info" field only) onto an already-loaded CIS
    # index (PSCustomObject, buckets -> key -> entry). Used by
    # Import-CisIndex; Build-CisIndex.ps1 applies the same logic separately
    # on its pre-serialization hashtable structure.
    param($CisIndex, [hashtable]$Overrides)
    if ($null -eq $CisIndex -or $null -eq $Overrides -or $Overrides.Count -eq 0) { return }
    foreach ($bucketName in $script:CisIndexBuckets) {
        $bucketObj = $CisIndex.$bucketName
        if ($null -eq $bucketObj) { continue }
        foreach ($prop in $bucketObj.PSObject.Properties) {
            $overrideKey = "$bucketName`::$($prop.Name)"
            if ($Overrides.ContainsKey($overrideKey)) {
                $prop.Value.info = $Overrides[$overrideKey].info
            }
        }
    }
}

function Get-CisIndexEntry {
    # Low-level lookup shared by the public functions below: a JSON bucket
    # (PSCustomObject) can't be indexed with [] like a hashtable - go through its properties instead.
    param($CisIndex, [string]$Bucket, [string]$Key)

    if ($null -eq $CisIndex -or [string]::IsNullOrEmpty($Key)) { return $null }
    $bucketObj = $CisIndex.$Bucket
    if ($null -eq $bucketObj) { return $null }
    $prop = $bucketObj.PSObject.Properties[$Key]
    if ($null -eq $prop) { return $null }
    return $prop.Value
}

function Get-CisRecommendationForRegistry {
    # Administrative Templates: matched by (registryKey, valueName), as
    # exposed by the ADMX index. registryKey is already hive-relative (no
    # "HKLM\"), like on the CIS side after normalization in Build-CisIndex.ps1.
    param($CisIndex, [string]$RegistryKey, [string]$ValueName)

    if ([string]::IsNullOrEmpty($RegistryKey) -or [string]::IsNullOrEmpty($ValueName)) { return $null }
    $key = "$($RegistryKey.ToLowerInvariant())|$($ValueName.ToLowerInvariant())"
    return Get-CisIndexEntry -CisIndex $CisIndex -Bucket 'byRegistry' -Key $key
}

function Get-CisRecommendationForSecuritySetting {
    # Security Settings: Password Policy / Account Lockout Policy (via the
    # manual mapping table) and User Rights Assignment (SecurityCatalog
    # name, e.g. SeBackupPrivilege, already matches the CIS right_type field as-is).
    param($CisIndex, [string]$Section, [string]$Name)

    if ($Section -eq 'Privilege Rights') {
        return Get-CisIndexEntry -CisIndex $CisIndex -Bucket 'byUserRight' -Key $Name
    }

    if ($Section -eq 'Registry Values') {
        # $Name has the form "MACHINE\<RegistryPath>\<ValueName>" (see
        # SecurityCatalog.ps1) - split it back to reuse the same byRegistry
        # matching as Administrative Templates.
        $withoutHive = $Name -replace '^MACHINE\\', ''
        $lastSlash = $withoutHive.LastIndexOf('\')
        if ($lastSlash -le 0) { return $null }
        $registryPath = $withoutHive.Substring(0, $lastSlash)
        $valueName = $withoutHive.Substring($lastSlash + 1)
        return Get-CisRecommendationForRegistry -CisIndex $CisIndex -RegistryKey $registryPath -ValueName $valueName
    }

    if ($script:CisPasswordLockoutKeyMap.ContainsKey($Name)) {
        $mapped = $script:CisPasswordLockoutKeyMap[$Name]
        return Get-CisIndexEntry -CisIndex $CisIndex -Bucket $mapped.Bucket -Key $mapped.Key
    }

    return $null
}

function Get-CisRecommendationForAuditSubcategory {
    # Advanced Audit Policy: matched by the English subcategory name
    # (AdvancedAuditCatalog.ps1's 'En' field), same as CIS's audit_policy_subcategory.
    param($CisIndex, [string]$SubcategoryNameEn)

    return Get-CisIndexEntry -CisIndex $CisIndex -Bucket 'byAuditSubcategory' -Key $SubcategoryNameEn
}

# ---------------------------------------------------------------------------
# Active CIS profile selection (View > Profile, see
# plan-gpedit-ui-enhancements.md §3.b): a single setting can have multiple
# recommendations (benchmark x version x level x role) that diverge across
# benchmark versions. Instead of aggregating, ambiguity is resolved via a
# single active profile chosen by the user.
# ---------------------------------------------------------------------------

$script:CisIndexBuckets = @('byRegistry', 'byPasswordPolicy', 'byLockoutPolicy', 'byUserRight', 'byAuditSubcategory')

function Get-CisAllEntries {
    # All entries (unique controls) of the CIS index, across all buckets -
    # each carries its own profiles[] array.
    param($CisIndex)

    $entries = New-Object System.Collections.Generic.List[object]
    # ", $entries" everywhere here: an unprotected return enumerates the
    # collection, so an EMPTY List[object] becomes $null for the caller.
    # Real bug found/fixed in Select-FilteredItems (GpEdit.ps1) -
    # applied here as a precaution since this can genuinely return 0
    # elements (CisIndex missing/empty).
    if ($null -eq $CisIndex) { return , $entries }
    foreach ($bucketName in $script:CisIndexBuckets) {
        $bucketObj = $CisIndex.$bucketName
        if ($null -eq $bucketObj) { continue }
        foreach ($prop in $bucketObj.PSObject.Properties) {
            $entries.Add($prop.Value)
        }
    }
    return , $entries
}

function Get-CisBenchmarkYear {
    # Benchmark name (e.g. "Microsoft Windows Server 2025") always carries
    # the Windows Server year - used as sort key for "most recent OS".
    param([string]$Benchmark)
    $m = [regex]::Match($Benchmark, '(\d{4})')
    if ($m.Success) { return [int]$m.Groups[1].Value }
    return 0
}

function Get-CisDistinctProfiles {
    <#
        Flat, deduplicated list of all profiles (benchmark, version, level,
        role) in the CIS index, sorted newest to oldest (benchmark year,
        then version, level, role) - feeds the View > Profile submenu.
    #>
    param($CisIndex)

    $seen = @{}
    $profiles = New-Object System.Collections.Generic.List[object]
    foreach ($entry in (Get-CisAllEntries -CisIndex $CisIndex)) {
        foreach ($p in @($entry.profiles)) {
            if ($null -eq $p) { continue }
            $key = "$($p.benchmark)|$($p.version)|$($p.level)|$($p.role)"
            if ($seen.ContainsKey($key)) { continue }
            $seen[$key] = $true
            $profiles.Add([pscustomobject]@{
                Benchmark = $p.benchmark
                Version   = $p.version
                Level     = $p.level
                Role      = $p.role
                Year      = Get-CisBenchmarkYear -Benchmark $p.benchmark
            })
        }
    }
    # ", [...]" (see Get-CisAllEntries comment above): without it, an empty
    # sorted result would become $null for the caller instead of an empty list.
    return , [System.Collections.Generic.List[object]]@(
        $profiles | Sort-Object -Property @(
            @{ Expression = 'Year'; Descending = $true },
            @{ Expression = 'Benchmark'; Descending = $false },
            @{ Expression = 'Version'; Descending = $true },
            @{ Expression = 'Level'; Descending = $false },
            @{ Expression = 'Role'; Descending = $false }
        )
    )
}

function Get-CisDefaultProfile {
    <#
        Default profile at startup: most recent OS, level L1, role Member
        Server (MS) - decided in plan-gpedit-ui-enhancements.md §3.b. Falls
        back to the first available profile (most recent, any level/role)
        if the exact L1/MS combo isn't in the index.
    #>
    param($CisIndex)

    $distinct = Get-CisDistinctProfiles -CisIndex $CisIndex
    if ($distinct.Count -eq 0) { return $null }

    $maxYear = ($distinct | Measure-Object -Property Year -Maximum).Maximum
    $preferred = $distinct | Where-Object { $_.Year -eq $maxYear -and $_.Level -eq 'L1' -and $_.Role -eq 'MS' } | Select-Object -First 1
    if ($preferred) { return $preferred }
    return $distinct[0]
}

function Get-CisMachineOsInfo {
    # Queries WMI/CIM (read-only, no elevation needed) for this machine's
    # OS role/version. $null if the query fails (restricted environment) -
    # caller should fall back to Get-CisDefaultProfile.
    try {
        $os = Get-CimInstance -ClassName Win32_OperatingSystem -ErrorAction Stop
        $cs = Get-CimInstance -ClassName Win32_ComputerSystem -ErrorAction Stop
        return [pscustomobject]@{
            Caption      = $os.Caption
            # ProductType (Win32_OperatingSystem): 1 = workstation,
            # 2 = domain controller, 3 = member server.
            ProductType  = $os.ProductType
            PartOfDomain = $cs.PartOfDomain
        }
    }
    catch {
        Write-Warning "Unable to determine the machine's OS (WMI): $($_.Exception.Message)"
        return $null
    }
}

function Get-CisMachineDefaultProfile {
    <#
        Default CIS profile reflecting THIS machine's actual OS
        version/role, rather than always the newest OS covered by the index
        (Get-CisDefaultProfile is the fallback if WMI detection fails or no
        index profile matches this machine - e.g. a Windows version not yet
        covered by a CIS benchmark). Always prefers L1 among candidates.

        Workstation: version (10/11) read from Caption; CIS "Enterprise"
        benchmark (domain-joined) is preferred over "Stand-alone" when
        PartOfDomain is true, and vice versa - reasonable heuristic, no
        more direct WMI signal exists for these two benchmark variants.
    #>
    param($CisIndex)

    $osInfo = Get-CisMachineOsInfo
    if ($null -eq $osInfo) { return $null }

    $distinct = Get-CisDistinctProfiles -CisIndex $CisIndex
    if ($distinct.Count -eq 0) { return $null }

    if ($osInfo.ProductType -eq 1) {
        $versionToken = if ($osInfo.Caption -match 'Windows\s*11') { '11' } elseif ($osInfo.Caption -match 'Windows\s*10') { '10' } else { $null }
        if (-not $versionToken) { return $null }
        $editionToken = if ($osInfo.PartOfDomain) { 'Enterprise' } else { 'Stand-alone' }
        $candidates = @($distinct | Where-Object { -not $_.Role -and $_.Benchmark -match "Windows\s*$versionToken\b" -and $_.Benchmark -match [regex]::Escape($editionToken) })
    }
    else {
        $role = if ($osInfo.ProductType -eq 2) { 'DC' } else { 'MS' }
        $yearMatch = [regex]::Match($osInfo.Caption, '(\d{4})')
        if (-not $yearMatch.Success) { return $null }
        $year = [int]$yearMatch.Groups[1].Value
        $candidates = @($distinct | Where-Object { $_.Role -eq $role -and $_.Year -eq $year })
    }

    if ($candidates.Count -eq 0) { return $null }
    $preferred = $candidates | Where-Object { $_.Level -eq 'L1' } | Select-Object -First 1
    if ($preferred) { return $preferred }
    return $candidates[0]
}

function Get-CisRecommendationValueForProfile {
    <#
        Extracts the recommended value (valueData) for the given active
        profile from an already-resolved CIS entry's profiles[] array.
        Returns $null if this setting has no recommendation for this exact
        profile (even if it has one for another) - this $null drives both
        the "Recommended state" column and the profile filter.
    #>
    param($CisEntry, $ActiveProfile, [hashtable]$Ui)

    if ($null -eq $CisEntry -or $null -eq $ActiveProfile) { return $null }
    foreach ($p in @($CisEntry.profiles)) {
        if ($null -eq $p) { continue }
        if ($p.benchmark -eq $ActiveProfile.Benchmark -and $p.version -eq $ActiveProfile.Version -and $p.level -eq $ActiveProfile.Level -and $p.role -eq $ActiveProfile.Role) {
            if ([string]::IsNullOrEmpty($p.valueData)) { return $null }
            if ($Ui) { return ($p.valueData -replace '\s*\|\|\s*', " $($Ui.CisOrWord) ") }
            return $p.valueData
        }
    }
    return $null
}

function Get-CisRecommendationStateText {
    <#
        Text following "The recommended state for this setting is:" in a
        resolved CIS entry's info field (extracted once by
        Build-CisIndex.ps1, see recommendedStateText). Shared across all of
        the entry's profiles (like title/info/valueType) - doesn't depend
        on the active profile, unlike Get-CisRecommendationValueForProfile.
        Feeds the "CIS States" column (Administrative Templates only).
    #>
    param($CisEntry)

    if ($null -eq $CisEntry) { return $null }
    return $CisEntry.recommendedStateText
}

