<#
    Maps settings managed by the app (Administrative Templates via
    registryKey/valueName, Security Settings via SecurityCatalog.ps1,
    Advanced Audit via AdvancedAuditCatalog.ps1) to CIS recommendations
    loaded from data/cis-index.json (generated by Build-CisIndex.ps1, see
    plan-gpedit-cis.md).

    The CIS index is never regenerated by GpEdit.ps1: unlike the
    ADMX/security indexes, its content doesn't depend on machine state,
    only on the versioned .audit files - regenerate manually
    (Build-CisIndex.ps1) only when new benchmarks are added.
#>

Set-StrictMode -Version Latest

# CIS vocabulary (password_policy / lockout_policy, SCREAMING_SNAKE_CASE) to
# SecurityCatalog.ps1 names (PascalCase). The two never align by
# construction (independent sources), hence this fixed table: CIS
# vocabulary for these ~10 settings has been stable since 2016 (checked
# against 15 available .audit files).
$script:CisPasswordLockoutKeyMap = @{
    PasswordHistorySize        = @{ Bucket = 'byPasswordPolicy'; Key = 'ENFORCE_PASSWORD_HISTORY' }
    MaximumPasswordAge         = @{ Bucket = 'byPasswordPolicy'; Key = 'MAXIMUM_PASSWORD_AGE' }
    MinimumPasswordAge         = @{ Bucket = 'byPasswordPolicy'; Key = 'MINIMUM_PASSWORD_AGE' }
    MinimumPasswordLength      = @{ Bucket = 'byPasswordPolicy'; Key = 'MINIMUM_PASSWORD_LENGTH' }
    PasswordComplexity         = @{ Bucket = 'byPasswordPolicy'; Key = 'COMPLEXITY_REQUIREMENTS' }
    ClearTextPassword          = @{ Bucket = 'byPasswordPolicy'; Key = 'REVERSIBLE_ENCRYPTION' }
    LockoutDuration            = @{ Bucket = 'byLockoutPolicy'; Key = 'LOCKOUT_DURATION' }
    LockoutBadCount            = @{ Bucket = 'byLockoutPolicy'; Key = 'LOCKOUT_THRESHOLD' }
    ResetLockoutCount          = @{ Bucket = 'byLockoutPolicy'; Key = 'LOCKOUT_RESET' }
    ForceLogoffWhenHourExpire  = @{ Bucket = 'byPasswordPolicy'; Key = 'FORCE_LOGOFF' }
}

function Import-CisIndex {
    <#
        Loads data/cis-index.json if present. Never regenerates it (see
        header comment): if missing, the CIS tab is just hidden everywhere
        (Get-CisRecommendation returns $null), without blocking app startup.

        Also applies "info" field overrides (data/cis-overrides.json, see
        plan-gpedit-security-catalog-editor.md §4.3) right after loading -
        on every launch, not just when Build-CisIndex.ps1 is manually rerun,
        so a UI edit stays visible without depending on a full regeneration.
    #>
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        Write-Warning "CIS index not found ($Path) - the 'CIS recommendation' tab will be hidden. Run Build-CisIndex.ps1 to generate it."
        return $null
    }
    try {
        $cisIndex = Get-Content -Raw -Encoding UTF8 -LiteralPath $Path | ConvertFrom-Json
        $overrides = Get-CisOverrides -DataPath (Split-Path -Parent $Path)
        Merge-CisOverrides -CisIndex $cisIndex -Overrides $overrides
        return $cisIndex
    }
    catch {
        Write-Warning "CIS index unreadable ($Path): $($_.Exception.Message) - the 'CIS recommendation' tab will be hidden."
        return $null
    }
}

# ---------------------------------------------------------------------------
# Live catalog editor - CIS "info" field overrides (see
# plan-gpedit-security-catalog-editor.md §4.3). data/cis-index.json is
# generated from .audit files (Build-CisIndex.ps1), so a manual edit
# written directly into it would be lost on the next regeneration.
# Overrides live in a separate file instead, keyed by "<bucket>::<key>"
# (same buckets/keys as cis-index.json), merged both here (Import-CisIndex,
# every launch) and in Build-CisIndex.ps1 (every full regeneration).
# ---------------------------------------------------------------------------

function Get-CisOverridesPath {
    param([string]$DataPath)
    return (Join-Path $DataPath 'cis-overrides.json')
}

function Get-CisOverrides {
    # Loads data/cis-overrides.json; missing/unreadable => no overrides
    # (same tolerance as a missing cis-index.json).
    param([string]$DataPath)
    $path = Get-CisOverridesPath -DataPath $DataPath
    if (-not (Test-Path -LiteralPath $path)) { return @{} }
    try {
        $raw = Get-Content -Raw -Encoding UTF8 -LiteralPath $path | ConvertFrom-Json
        $result = @{}
        foreach ($prop in $raw.PSObject.Properties) {
            $result[$prop.Name] = @{ info = $prop.Value.info }
        }
        return $result
    }
    catch {
        Write-Warning "CIS overrides unreadable ($path): $($_.Exception.Message) - ignored."
        return @{}
    }
}

# ---------------------------------------------------------------------------
# Fallback CIS matching (cis-fallback-map.json) - second-chance lookup for
# CIS entries whose .audit fields alone can't produce a match key/aren't
# reachable from a given Security Options section (e.g. ANONYMOUS_SID_SETTING
# / REG_CHECK entries with no reg_key, or a "System Access" setting with no
# registry backing at all, like "Network access: Allow anonymous SID/Name
# translation"). Keyed by normalized CIS title (not CIS number: the same
# setting's number shifts between benchmark versions/profiles). Populated by
# Build-CisIndex.ps1 (auto-resolved via SecurityCatalog/ADMX where possible),
# editable by hand for cases neither source can resolve.
# ---------------------------------------------------------------------------

function Get-CisFallbackMapPath {
    param([string]$DataPath)
    return (Join-Path $DataPath 'cis-fallback-map.json')
}

function Test-CisFallbackMapEntry {
    # An entry is only usable if it carries a valueType and either a
    # complete (regKey, regItem) pair or an explicit "no registry backing"
    # marker (regKey/regItem both $null, not just missing) - guards against
    # a malformed manual edit (e.g. only regKey filled in) silently
    # producing a broken byTitle entry.
    param($Entry)

    if ($null -eq $Entry) { return $false }
    if ([string]::IsNullOrEmpty($Entry.valueType)) { return $false }
    $hasRegKey = -not [string]::IsNullOrEmpty($Entry.regKey)
    $hasRegItem = -not [string]::IsNullOrEmpty($Entry.regItem)
    if ($hasRegKey -ne $hasRegItem) { return $false }
    return $true
}

function Get-CisFallbackMap {
    # Loads cis-fallback-map.json; missing/unreadable => no fallback entries
    # (same tolerance as Get-CisOverrides/a missing cis-index.json). Entries
    # failing Test-CisFallbackMapEntry are skipped individually with a
    # warning rather than discarding the whole file.
    param([string]$DataPath)
    $path = Get-CisFallbackMapPath -DataPath $DataPath
    if (-not (Test-Path -LiteralPath $path)) { return @{} }
    try {
        $raw = Get-Content -Raw -Encoding UTF8 -LiteralPath $path | ConvertFrom-Json
        $result = @{}
        foreach ($prop in $raw.PSObject.Properties) {
            if (-not (Test-CisFallbackMapEntry -Entry $prop.Value)) {
                Write-Warning "CIS fallback map entry ignored (malformed, title: '$($prop.Name)') in $path"
                continue
            }
            $result[$prop.Name] = $prop.Value
        }
        return $result
    }
    catch {
        Write-Warning "CIS fallback map unreadable ($path): $($_.Exception.Message) - ignored."
        return @{}
    }
}

function Set-CisOverride {
    <#
        Adds/replaces the "info" override of a CIS entry (identified by its
        bucket + key, from the resolved entry - see Get-CisRecommendationFor...
        in this file) and rewrites data/cis-overrides.json in full (small
        file, no performance concern).
    #>
    param(
        [Parameter(Mandatory)][string]$DataPath,
        [Parameter(Mandatory)][string]$Bucket,
        [Parameter(Mandatory)][string]$Key,
        [Parameter(Mandatory)][string]$Info
    )
    $path = Get-CisOverridesPath -DataPath $DataPath
    $overrides = Get-CisOverrides -DataPath $DataPath
    $overrides["$Bucket`::$Key"] = @{ info = $Info }

    $ordered = [ordered]@{}
    foreach ($k in ($overrides.Keys | Sort-Object)) { $ordered[$k] = $overrides[$k] }

    $outDir = Split-Path -Parent $path
    if (-not (Test-Path -LiteralPath $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
    $json = $ordered | ConvertTo-Json -Depth 5
    [System.IO.File]::WriteAllText($path, $json, (New-Object System.Text.UTF8Encoding($true)))
}

function ConvertTo-CisNormalizedTitle {
    # Shared normalization for the byTitle fallback bucket: same casing/
    # whitespace/"(L1)"/"(L2)" stripping as ConvertTo-CisNumberAndTitle
    # (Build-CisIndex.ps1) applies to the title portion of "description",
    # so a title built at index time and one built at runtime (from a
    # SecurityCatalog DisplayName) collide on the same key.
    param([string]$Title)

    if ([string]::IsNullOrEmpty($Title)) { return $null }
    $normalized = $Title -replace '^\(L\d\)\s*', ''
    $normalized = ($normalized -replace '\s+', ' ').Trim().ToLowerInvariant()
    if ([string]::IsNullOrEmpty($normalized)) { return $null }
    return $normalized
}

function Get-CisSettingNameFromTitle {
    # byTitle must be keyed by something the app actually has at runtime
    # when the primary (Registry Values/Privilege Rights/password-lockout
    # map) match misses: that's a bare SecurityCatalog/ADMX DisplayName
    # (e.g. "Network access: Allow anonymous SID/Name translation"), never
    # the full CIS sentence. Extracts the quoted setting name from a CIS
    # title of the form "Ensure '<setting name>' is set to '<value>'"
    # (optionally suffixed "(DC Only)"/"(MS Only)") - that quoted name is
    # exactly the DisplayName in SecurityCatalog/ADMX. Falls back to the
    # whole title for the rare CIS title that doesn't follow this pattern
    # (then a byTitle match would need the runtime DisplayName to equal
    # that whole title, which won't happen - effectively unreachable via
    # the fallback map for such a title, same as no fallback at all).
    param([string]$Title)

    if ([string]::IsNullOrEmpty($Title)) { return $Title }
    $m = [regex]::Match($Title, "^Ensure\s+'(?<name>.+?)'\s+is\s+set\s+to\s+")
    if ($m.Success) { return $m.Groups['name'].Value }
    return $Title
}

function Get-CisIndexBucket {
    # Safe accessor for a bucket on the loaded CIS index (PSCustomObject
    # from ConvertFrom-Json): plain dot access ($CisIndex.$BucketName)
    # throws under Set-StrictMode -Version Latest (this file's mode) when
    # the property is genuinely absent - which happens for any
    # cis-index.json cached on disk from before a bucket was added (e.g.
    # byTitle), since Import-CisIndex never regenerates it on its own (see
    # its header comment) and the audit-files fingerprint that gates a
    # rebuild doesn't change just because the app's bucket list did.
    param($CisIndex, [string]$BucketName)

    if ($null -eq $CisIndex) { return $null }
    $prop = $CisIndex.PSObject.Properties[$BucketName]
    if ($null -eq $prop) { return $null }
    return $prop.Value
}

function Merge-CisOverrides {
    # Applies overrides ("info" field only) onto an already-loaded CIS
    # index (PSCustomObject, buckets -> key -> entry). Used by
    # Import-CisIndex; Build-CisIndex.ps1 applies the same logic separately
    # on its pre-serialization hashtable structure.
    param($CisIndex, [hashtable]$Overrides)
    if ($null -eq $CisIndex -or $null -eq $Overrides -or $Overrides.Count -eq 0) { return }
    foreach ($bucketName in $script:CisIndexBuckets) {
        $bucketObj = Get-CisIndexBucket -CisIndex $CisIndex -BucketName $bucketName
        if ($null -eq $bucketObj) { continue }
        foreach ($prop in $bucketObj.PSObject.Properties) {
            $overrideKey = "$bucketName`::$($prop.Name)"
            if ($Overrides.ContainsKey($overrideKey)) {
                $prop.Value.info = $Overrides[$overrideKey].info
            }
        }
    }
}

function Get-CisIndexEntry {
    # Low-level lookup shared by the public functions below: a JSON bucket
    # (PSCustomObject) can't be indexed with [] like a hashtable - go through its properties instead.
    param($CisIndex, [string]$Bucket, [string]$Key)

    if ($null -eq $CisIndex -or [string]::IsNullOrEmpty($Key)) { return $null }
    $bucketObj = Get-CisIndexBucket -CisIndex $CisIndex -BucketName $Bucket
    if ($null -eq $bucketObj) { return $null }
    $prop = $bucketObj.PSObject.Properties[$Key]
    if ($null -eq $prop) { return $null }
    return $prop.Value
}

function Get-CisRecommendationForRegistry {
    # Administrative Templates: matched by (registryKey, valueName), as
    # exposed by the ADMX index. registryKey is already hive-relative (no
    # "HKLM\"), like on the CIS side after normalization in Build-CisIndex.ps1.
    param($CisIndex, [string]$RegistryKey, [string]$ValueName)

    if ([string]::IsNullOrEmpty($RegistryKey) -or [string]::IsNullOrEmpty($ValueName)) { return $null }
    $key = "$($RegistryKey.ToLowerInvariant())|$($ValueName.ToLowerInvariant())"
    return Get-CisIndexEntry -CisIndex $CisIndex -Bucket 'byRegistry' -Key $key
}

function Get-CisRecommendationForSecuritySetting {
    # Security Settings: Password Policy / Account Lockout Policy (via the
    # manual mapping table) and User Rights Assignment (SecurityCatalog
    # name, e.g. SeBackupPrivilege, already matches the CIS right_type field as-is).
    #
    # Each branch below is the authoritative match for its section (built
    # from real .audit fields) and falls through - rather than returning
    # immediately - on a miss, so a setting that isn't found there still
    # gets a chance via the generic byTitle fallback at the end. That
    # fallback is what covers a section with no primary match path at all
    # (e.g. "System Access" settings with no registry backing, such as
    # "Network access: Allow anonymous SID/Name translation") without
    # requiring a dedicated branch per section - see cis-fallback-map.json.
    param($CisIndex, [string]$Section, [string]$Name, [string]$DisplayName)

    if ($Section -eq 'Privilege Rights') {
        $rec = Get-CisIndexEntry -CisIndex $CisIndex -Bucket 'byUserRight' -Key $Name
        if ($rec) { return $rec }
    }

    if ($Section -eq 'Registry Values') {
        # $Name has the form "MACHINE\<RegistryPath>\<ValueName>" (see
        # SecurityCatalog.ps1) - split it back to reuse the same byRegistry
        # matching as Administrative Templates.
        $withoutHive = $Name -replace '^MACHINE\\', ''
        $lastSlash = $withoutHive.LastIndexOf('\')
        if ($lastSlash -gt 0) {
            $registryPath = $withoutHive.Substring(0, $lastSlash)
            $valueName = $withoutHive.Substring($lastSlash + 1)
            $rec = Get-CisRecommendationForRegistry -CisIndex $CisIndex -RegistryKey $registryPath -ValueName $valueName
            if ($rec) { return $rec }
        }
    }

    if ($script:CisPasswordLockoutKeyMap.ContainsKey($Name)) {
        $mapped = $script:CisPasswordLockoutKeyMap[$Name]
        $rec = Get-CisIndexEntry -CisIndex $CisIndex -Bucket $mapped.Bucket -Key $mapped.Key
        if ($rec) { return $rec }
    }

    $normalizedTitle = ConvertTo-CisNormalizedTitle -Title $DisplayName
    if ($normalizedTitle) {
        $rec = Get-CisIndexEntry -CisIndex $CisIndex -Bucket 'byTitle' -Key $normalizedTitle
        if ($rec) { return $rec }
    }

    return $null
}

function Get-CisRecommendationForAuditSubcategory {
    # Advanced Audit Policy: matched by the English subcategory name
    # (AdvancedAuditCatalog.ps1's 'En' field), same as CIS's audit_policy_subcategory.
    param($CisIndex, [string]$SubcategoryNameEn)

    return Get-CisIndexEntry -CisIndex $CisIndex -Bucket 'byAuditSubcategory' -Key $SubcategoryNameEn
}

# ---------------------------------------------------------------------------
# Active CIS profile selection (View > Profile, see
# plan-gpedit-ui-enhancements.md §3.b): a single setting can have multiple
# recommendations (benchmark x version x level x role) that diverge across
# benchmark versions. Instead of aggregating, ambiguity is resolved via a
# single active profile chosen by the user.
# ---------------------------------------------------------------------------

$script:CisIndexBuckets = @('byRegistry', 'byPasswordPolicy', 'byLockoutPolicy', 'byUserRight', 'byAuditSubcategory', 'byTitle')

function Get-CisAllEntries {
    # All entries (unique controls) of the CIS index, across all buckets -
    # each carries its own profiles[] array.
    param($CisIndex)

    $entries = New-Object System.Collections.Generic.List[object]
    # ", $entries" everywhere here: an unprotected return enumerates the
    # collection, so an EMPTY List[object] becomes $null for the caller.
    # Real bug found/fixed in Select-FilteredItems (GpEdit.ps1) -
    # applied here as a precaution since this can genuinely return 0
    # elements (CisIndex missing/empty).
    if ($null -eq $CisIndex) { return , $entries }
    foreach ($bucketName in $script:CisIndexBuckets) {
        $bucketObj = Get-CisIndexBucket -CisIndex $CisIndex -BucketName $bucketName
        if ($null -eq $bucketObj) { continue }
        foreach ($prop in $bucketObj.PSObject.Properties) {
            $entries.Add($prop.Value)
        }
    }
    return , $entries
}

function Get-CisBenchmarkYear {
    # Benchmark name (e.g. "Microsoft Windows Server 2025") always carries
    # the Windows Server year - used as sort key for "most recent OS".
    param([string]$Benchmark)
    $m = [regex]::Match($Benchmark, '(\d{4})')
    if ($m.Success) { return [int]$m.Groups[1].Value }
    return 0
}

function Get-CisDistinctProfiles {
    <#
        Flat, deduplicated list of all profiles (benchmark, version, level,
        role) in the CIS index, sorted newest to oldest (benchmark year,
        then version, level, role) - feeds the View > Profile submenu.
    #>
    param($CisIndex)

    $seen = @{}
    $profiles = New-Object System.Collections.Generic.List[object]
    foreach ($entry in (Get-CisAllEntries -CisIndex $CisIndex)) {
        foreach ($p in @($entry.profiles)) {
            if ($null -eq $p) { continue }
            $key = "$($p.benchmark)|$($p.version)|$($p.level)|$($p.role)"
            if ($seen.ContainsKey($key)) { continue }
            $seen[$key] = $true
            $profiles.Add([pscustomobject]@{
                Benchmark = $p.benchmark
                Version   = $p.version
                Level     = $p.level
                Role      = $p.role
                Year      = Get-CisBenchmarkYear -Benchmark $p.benchmark
            })
        }
    }
    # ", [...]" (see Get-CisAllEntries comment above): without it, an empty
    # sorted result would become $null for the caller instead of an empty list.
    return , [System.Collections.Generic.List[object]]@(
        $profiles | Sort-Object -Property @(
            @{ Expression = 'Year'; Descending = $true },
            @{ Expression = 'Benchmark'; Descending = $false },
            @{ Expression = 'Version'; Descending = $true },
            @{ Expression = 'Level'; Descending = $false },
            @{ Expression = 'Role'; Descending = $false }
        )
    )
}

function Get-CisDefaultProfile {
    <#
        Default profile at startup: most recent OS, level L1, role Member
        Server (MS) - decided in plan-gpedit-ui-enhancements.md §3.b. Falls
        back to the first available profile (most recent, any level/role)
        if the exact L1/MS combo isn't in the index.
    #>
    param($CisIndex)

    $distinct = Get-CisDistinctProfiles -CisIndex $CisIndex
    if ($distinct.Count -eq 0) { return $null }

    $maxYear = ($distinct | Measure-Object -Property Year -Maximum).Maximum
    $preferred = $distinct | Where-Object { $_.Year -eq $maxYear -and $_.Level -eq 'L1' -and $_.Role -eq 'MS' } | Select-Object -First 1
    if ($preferred) { return $preferred }
    return $distinct[0]
}

function Get-CisMachineOsInfo {
    # Queries WMI/CIM (read-only, no elevation needed) for this machine's
    # OS role/version. $null if the query fails (restricted environment) -
    # caller should fall back to Get-CisDefaultProfile.
    try {
        $os = Get-CimInstance -ClassName Win32_OperatingSystem -ErrorAction Stop
        $cs = Get-CimInstance -ClassName Win32_ComputerSystem -ErrorAction Stop
        return [pscustomobject]@{
            Caption      = $os.Caption
            # ProductType (Win32_OperatingSystem): 1 = workstation,
            # 2 = domain controller, 3 = member server.
            ProductType  = $os.ProductType
            PartOfDomain = $cs.PartOfDomain
        }
    }
    catch {
        Write-Warning "Unable to determine the machine's OS (WMI): $($_.Exception.Message)"
        return $null
    }
}

function Get-CisMachineDefaultProfile {
    <#
        Default CIS profile reflecting THIS machine's actual OS
        version/role, rather than always the newest OS covered by the index
        (Get-CisDefaultProfile is the fallback if WMI detection fails or no
        index profile matches this machine - e.g. a Windows version not yet
        covered by a CIS benchmark). Always prefers L1 among candidates.

        Workstation: version (10/11) read from Caption; CIS "Enterprise"
        benchmark (domain-joined) is preferred over "Stand-alone" when
        PartOfDomain is true, and vice versa - reasonable heuristic, no
        more direct WMI signal exists for these two benchmark variants.
    #>
    param($CisIndex)

    $osInfo = Get-CisMachineOsInfo
    if ($null -eq $osInfo) { return $null }

    $distinct = Get-CisDistinctProfiles -CisIndex $CisIndex
    if ($distinct.Count -eq 0) { return $null }

    if ($osInfo.ProductType -eq 1) {
        $versionToken = if ($osInfo.Caption -match 'Windows\s*11') { '11' } elseif ($osInfo.Caption -match 'Windows\s*10') { '10' } else { $null }
        if (-not $versionToken) { return $null }
        $editionToken = if ($osInfo.PartOfDomain) { 'Enterprise' } else { 'Stand-alone' }
        $candidates = @($distinct | Where-Object { -not $_.Role -and $_.Benchmark -match "Windows\s*$versionToken\b" -and $_.Benchmark -match [regex]::Escape($editionToken) })
    }
    else {
        $role = if ($osInfo.ProductType -eq 2) { 'DC' } else { 'MS' }
        $yearMatch = [regex]::Match($osInfo.Caption, '(\d{4})')
        if (-not $yearMatch.Success) { return $null }
        $year = [int]$yearMatch.Groups[1].Value
        $candidates = @($distinct | Where-Object { $_.Role -eq $role -and $_.Year -eq $year })
    }

    if ($candidates.Count -eq 0) { return $null }
    $preferred = $candidates | Where-Object { $_.Level -eq 'L1' } | Select-Object -First 1
    if ($preferred) { return $preferred }
    return $candidates[0]
}

function Get-CisRecommendationValueForProfile {
    <#
        Extracts the recommended value (valueData) for the given active
        profile from an already-resolved CIS entry's profiles[] array.
        Returns $null if this setting has no recommendation for this exact
        profile (even if it has one for another) - this $null drives both
        the "Recommended state" column and the profile filter.
    #>
    param($CisEntry, $ActiveProfile, [hashtable]$Ui)

    if ($null -eq $CisEntry -or $null -eq $ActiveProfile) { return $null }
    foreach ($p in @($CisEntry.profiles)) {
        if ($null -eq $p) { continue }
        if ($p.benchmark -eq $ActiveProfile.Benchmark -and $p.version -eq $ActiveProfile.Version -and $p.level -eq $ActiveProfile.Level -and $p.role -eq $ActiveProfile.Role) {
            if ([string]::IsNullOrEmpty($p.valueData)) { return $null }
            if ($Ui) { return ($p.valueData -replace '\s*\|\|\s*', " $($Ui.CisOrWord) ") }
            return $p.valueData
        }
    }
    return $null
}

# ---------------------------------------------------------------------------
# "New Group Policy > CIS Gap-fill/Full compliance" generation (see
# plan-gpedit-new-gpo-cis-generation.md) - best-effort mapping from a
# resolved CIS recommended value (Get-CisRecommendationValueForProfile) to a
# concrete write for the app's own pipeline (Save-AdmxChangeToFile/
# Save-SecurityChangeToFile/Save-AdvancedAuditChangeToFile). Only value
# shapes that can be resolved with confidence are handled; anything else
# returns $null so the caller can list it as "not covered" in the generation
# summary instead of guessing (plan §8 point 5).
# ---------------------------------------------------------------------------

# The 4 organization-specific items (plan §4.3) - no universal recommended
# value exists for any of them, so they're never auto-filled: the
# "Organization-specific values" screen collects them from the user instead.
# Order matches the plan §4.3 mockup.
$script:CisOrgValueKeys = @('RenameAdministratorAccount', 'RenameGuestAccount', 'LogonMessageTitle', 'LogonMessageText')

function Test-CisOrgValueEntryInProfile {
    # Whether $Entry (a byOrgValue entry) is actually recommended for
    # $ActiveProfile - same (benchmark, version, level, role) match as
    # Get-CisRecommendationValueForProfile, but presence-only: these
    # entries carry no meaningful valueData to extract.
    param($Entry, $ActiveProfile)
    if ($null -eq $Entry -or $null -eq $ActiveProfile) { return $false }
    foreach ($p in @($Entry.profiles)) {
        if ($null -eq $p) { continue }
        if ($p.benchmark -eq $ActiveProfile.Benchmark -and $p.version -eq $ActiveProfile.Version -and $p.level -eq $ActiveProfile.Level -and $p.role -eq $ActiveProfile.Role) { return $true }
    }
    return $false
}

function Get-CisOrgValueEntries {
    <#
        "New Group Policy > CIS Gap-fill/Full compliance", screen 2->3 gate
        (plan §4.3/§4.4): which of the (at most 4) organization-specific
        items are actually recommended by AT LEAST ONE of the chosen
        profile(s) (L1 alone, or L1+L2 union). Returns a list of
        [pscustomobject]@{ Key; Title; Info } in the fixed §4.3 field order
        - empty (never $null) if none apply, so the caller can skip the
        "Organization-specific values" screen entirely, as the plan
        prescribes ("screen absent if the profile contains none").
    #>
    param($CisIndex, [System.Collections.Generic.List[object]]$ActiveProfiles)

    $result = New-Object System.Collections.Generic.List[object]
    $bucket = Get-CisIndexBucket -CisIndex $CisIndex -BucketName 'byOrgValue'
    if ($null -eq $bucket) { return , $result }

    foreach ($key in $script:CisOrgValueKeys) {
        $prop = $bucket.PSObject.Properties[$key]
        if ($null -eq $prop) { continue }
        $entry = $prop.Value
        $isRecommended = $false
        foreach ($activeProfile in $ActiveProfiles) {
            if (Test-CisOrgValueEntryInProfile -Entry $entry -ActiveProfile $activeProfile) { $isRecommended = $true; break }
        }
        if ($isRecommended) {
            $result.Add([pscustomobject]@{ Key = $key; Title = $entry.title; Info = $entry.info })
        }
    }
    return , $result
}

function Get-CisFirstAlternativeValue {
    <#
        A recommended value can be an alternative ("A" || "B", see
        plan-gpedit-cis.md §5.2) - generation can only write ONE concrete
        value, so this takes the FIRST alternative exactly as written in
        the source .audit file (a deliberate, documented simplification,
        not an attempt to pick the "loosest"/"strictest" option). Also
        strips the surrounding quotes .audit values are always wrapped in.
    #>
    param([string]$RawValueData)
    if ([string]::IsNullOrWhiteSpace($RawValueData)) { return $RawValueData }
    $first = ($RawValueData -split '\|\|')[0].Trim()
    if ($first.Length -ge 2 -and $first.StartsWith('"') -and $first.EndsWith('"')) {
        $first = $first.Substring(1, $first.Length - 2)
    }
    return $first
}

function ConvertTo-CisBooleanValue {
    # 'Enabled'/'1'/'true' -> 1, 'Disabled'/'0'/'false' -> 0, else $null.
    param([string]$Text)
    if ([string]::IsNullOrWhiteSpace($Text)) { return $null }
    switch ($Text.Trim().ToLowerInvariant()) {
        { $_ -in @('enabled', '1', 'true') } { return 1 }
        { $_ -in @('disabled', '0', 'false') } { return 0 }
        default { return $null }
    }
}

function ConvertTo-CisAuditSettingValue {
    <#
        CIS text ("Success", "Failure", "Success and Failure"/"Success,
        Failure", "No Auditing") -> the 0-3 int audit.csv/classic Audit
        Policy expect (0 = No Auditing, 1 = Success, 2 = Failure, 3 =
        Success and Failure - see AuditCsvFile.ps1 header). $null if
        neither keyword is recognizable.
    #>
    param([string]$Text)
    if ([string]::IsNullOrWhiteSpace($Text)) { return $null }
    $t = $Text.ToLowerInvariant()
    $hasSuccess = $t -match 'success'
    $hasFailure = $t -match 'fail'
    if ($hasSuccess -and $hasFailure) { return 3 }
    if ($hasFailure) { return 2 }
    if ($hasSuccess) { return 1 }
    if ($t -match 'no audit') { return 0 }
    return $null
}

function Resolve-CisAdmxWrite {
    <#
        Best-effort mapping from a CIS recommended value to a concrete ADMX
        write (state + element values, ready for Save-AdmxChangeToFile).
        Only two shapes are handled with confidence:
          - a plain registryKey/valueName toggle (no elements): the
            recommended value is compared to the policy's own
            enabledValue/disabledValue - reliable because a CIS registry
            check for a toggle ADMX setting is, in practice, exactly the
            same literal registry value the policy itself writes for
            Enabled/Disabled.
          - a policy with exactly one 'decimal' element and a purely
            numeric recommended value: Enabled + that element set to the
            number.
        Anything else (multiple elements, enum/text/list-only elements, a
        recommended value that matches neither shape) is left unresolved
        ($null) rather than guessed.
    #>
    param($Policy, [string]$RecommendedValue)

    $value = Get-CisFirstAlternativeValue -RawValueData $RecommendedValue
    if ([string]::IsNullOrWhiteSpace($value)) { return $null }

    $elements = @($Policy.elements)
    if (-not $Policy.valueName -and $elements.Count -eq 0) { return $null }

    if ($elements.Count -eq 0) {
        if ($null -ne $Policy.enabledValue -and "$value" -eq "$($Policy.enabledValue)") {
            return [pscustomobject]@{ State = 'Enabled'; ElementValues = @{} }
        }
        if ($null -ne $Policy.disabledValue -and "$value" -eq "$($Policy.disabledValue)") {
            return [pscustomobject]@{ State = 'Disabled'; ElementValues = @{} }
        }
        $lower = $value.ToLowerInvariant()
        if ($lower -eq 'enabled' -and $null -ne $Policy.enabledValue) {
            return [pscustomobject]@{ State = 'Enabled'; ElementValues = @{} }
        }
        if ($lower -eq 'disabled' -and $null -ne $Policy.disabledValue) {
            return [pscustomobject]@{ State = 'Disabled'; ElementValues = @{} }
        }
        return $null
    }

    if ($elements.Count -eq 1 -and $elements[0].type -eq 'decimal' -and $value -match '^\d+$') {
        return [pscustomobject]@{ State = 'Enabled'; ElementValues = @{ ($elements[0].id) = [int]$value } }
    }

    return $null
}

function Resolve-CisSecurityWrite {
    <#
        Equivalent of Resolve-CisAdmxWrite for a Security Settings catalog
        entry (Get-SecurityCatalogEntries shape): returns
        [pscustomobject]@{ Value = <raw string ready for
        Save-SecurityChangeToFile> } or $null if the recommended text can't
        be confidently parsed for this entry's ValueType.
    #>
    param($Setting, [string]$RecommendedValue)

    $value = Get-CisFirstAlternativeValue -RawValueData $RecommendedValue
    if ([string]::IsNullOrWhiteSpace($value)) { return $null }

    switch ($Setting.valueType) {
        'boolean' {
            $b = ConvertTo-CisBooleanValue -Text $value
            if ($null -eq $b) { return $null }
            return [pscustomobject]@{ Value = "$b" }
        }
        'audit' {
            $a = ConvertTo-CisAuditSettingValue -Text $value
            if ($null -eq $a) { return $null }
            return [pscustomobject]@{ Value = "$a" }
        }
        { $_ -in @('minutes-or-forever', 'minutes', 'days', 'attempts', 'count') } {
            if ($value -match '(?<n>-?\d+)') { return [pscustomobject]@{ Value = $Matches['n'] } }
            return $null
        }
        'principal-list' {
            # "No One" (any casing) => explicitly configured, empty list.
            # Otherwise best-effort NTAccount.Translate per comma-separated
            # name; a name that fails to resolve (unknown/renamed built-in,
            # non-English OS) is dropped silently rather than failing the
            # whole entry - unresolved ($null) only if NOTHING translated.
            if ($value.Trim().ToLowerInvariant() -eq 'no one') { return [pscustomobject]@{ Value = '' } }
            $tokens = New-Object System.Collections.Generic.List[string]
            foreach ($name in ($value -split ',')) {
                $trimmed = $name.Trim()
                if (-not $trimmed) { continue }
                try {
                    $account = New-Object System.Security.Principal.NTAccount($trimmed)
                    $sid = $account.Translate([System.Security.Principal.SecurityIdentifier]).Value
                    $tokens.Add("*$sid")
                }
                catch { continue }
            }
            if ($tokens.Count -eq 0) { return $null }
            return [pscustomobject]@{ Value = (ConvertFrom-PrivilegeMemberList -Members $tokens) }
        }
        'reg-boolean' {
            $b = ConvertTo-CisBooleanValue -Text $value
            if ($null -eq $b) { return $null }
            return [pscustomobject]@{ Value = (ConvertTo-RegistryValuesEncoding -RegType $Setting.regType -Data "$b") }
        }
        'reg-number' {
            if ($value -match '(?<n>-?\d+)') { return [pscustomobject]@{ Value = (ConvertTo-RegistryValuesEncoding -RegType $Setting.regType -Data $Matches['n']) } }
            return $null
        }
        'reg-enum' {
            $choice = @($Setting.choices) | Where-Object { $value -match [regex]::Escape($_.displayName) -or "$($_.value)" -eq $value } | Select-Object -First 1
            if (-not $choice) { return $null }
            return [pscustomobject]@{ Value = (ConvertTo-RegistryValuesEncoding -RegType $Setting.regType -Data "$($choice.value)") }
        }
        # reg-string / reg-multistring / reg-flags: free-text/bitmask values
        # too ambiguous to auto-fill reliably from CIS wording - out of
        # scope for this pass (listed as "not covered" in the summary).
        default { return $null }
    }
}

function Get-CisRecommendationStateText {
    <#
        Text following "The recommended state for this setting is:" in a
        resolved CIS entry's info field (extracted once by
        Build-CisIndex.ps1, see recommendedStateText). Shared across all of
        the entry's profiles (like title/info/valueType) - doesn't depend
        on the active profile, unlike Get-CisRecommendationValueForProfile.
        Feeds the "CIS States" column (Administrative Templates only).
    #>
    param($CisEntry)

    if ($null -eq $CisEntry) { return $null }
    return $CisEntry.recommendedStateText
}

